### ISSUE TITLE
Setup CI for backend

### ISSUE THREAD

**Issue by coffeemakingtoaster** [incompetent-hosting-provider/monorepo#16]
CI should do at least:

- [x] code check (linter)
- [x] tests
- [x] build for multiple plattforms
- [x] docker build and publish to ghcr
- [x] Code coverage

Nice to have:
- [ ] automatically create github release on git tag on main branch

**Comment by lululujojo123** [comment]
Updated the ToDo description of that issue

**Comment by coffeemakingtoaster** [comment]
As a side note
Codecov io in a monorepository example: https://github.com/world-wide-weights/wwweights/blob/main/.github/workflows/auth-backend-ci.yml#L59
The lint action we talked about the other day:
https://github.com/golangci/golangci-lint-action

**Comment by lululujojo123** [comment]
[![codecov](https://codecov.io/gh/incompetent-hosting-provider/monorepo/graph/badge.svg?token=TDMQFMTP5C)](https://codecov.io/gh/incompetent-hosting-provider/monorepo)
